'use client'

import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import type { Spec } from '@/types'
import { Terminal, FileDown } from 'lucide-react'
import { useTranslations } from '@/i18n/useTranslations'
import { markdownComponents } from '@/components/markdown/markdownComponents'

interface SpecsViewProps {
  spec: Spec
}

export function SpecsView({ spec }: SpecsViewProps) {
  const { t } = useTranslations()

  const handleDownload = () => {
    const blob = new Blob([spec.content], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'dev-specs.md'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="overflow-hidden rounded-2xl border border-black/[0.08] bg-white shadow-sm dark:border-white/10 dark:bg-[#111111]">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-black/[0.08] bg-[#fafafa] px-6 py-4 dark:border-white/10 dark:bg-black">
        <div className="flex items-center gap-3">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#111111] dark:bg-white">
            <Terminal className="h-4 w-4 text-white dark:text-black" strokeWidth={2} />
          </div>
          <div>
            <h2 className="text-sm font-semibold text-[#111111] dark:text-[#ededed]">
              {t.specs.title}
            </h2>
            <p className="text-xs text-[#888888]">
              Generated by Arki -{' '}
              {new Date(spec.createdAt).toLocaleDateString()}
            </p>
          </div>
        </div>
        <button
          onClick={handleDownload}
          className="inline-flex items-center gap-2 rounded-xl border border-black/[0.08] bg-white px-4 py-2 text-sm font-semibold text-[#111111] transition-colors hover:bg-[#f0f0f0] dark:border-white/10 dark:bg-[#111111] dark:text-[#ededed] dark:hover:bg-[#1a1a1a]"
        >
          <FileDown className="h-4 w-4" strokeWidth={2} />
          {t.specs.downloadLabel}
        </button>
      </div>

      {/* Content */}
      <div className="px-8 py-8">
        <ReactMarkdown components={markdownComponents} remarkPlugins={[remarkGfm]}>
          {spec.content}
        </ReactMarkdown>
      </div>
    </div>
  )
}
